version: 2

models:
  - name: hub_purchase_order
    description: Hub for Purchase order data
    columns:
      - name: Purchase_order_hky
        description: Hashkey for PO Hub
        data_tests:
          - not_null
      - name: LDTS
        description: Loaded date
        data_tests:
          - not_null
      - name: LLOAD_ID
        description: Load id
        data_tests:
          - not_null
      - name: Record_Source2
        description: Source of the loaded record
        data_tests:
          - not_null
      - name: Purchase_order_bk
        description: Purchase order business key
        data_tests:
          - not_null
                   
  - name: hub_product
    description: Hub for Product data
    columns:
      - name: Product_hky
        description: Hashkey for Product Hub
        data_tests:
          - not_null          
      - name: LDTS
        description: Loaded date
        data_tests:
          - not_null
      - name: LLOAD_ID
        description: Load id
        data_tests:
          - not_null
      - name: Record_Source2
        description: Source of the loaded record
        data_tests:
          - not_null
      - name: Product_bk
        description: Product business key
        data_tests:
          - not_null
          
  - name: sat_product
    description: Satellite for Product data
    columns:
      - name: Product_hky
        description: Hashkey for Product Hub
        data_tests:
          - not_null          
      - name: LDTS
        description: Loaded date
        data_tests:
          - not_null
      - name: DELETE_FLAG
        description: See if the data is deleted
        data_tests:
          - not_null
      - name: CATEGORY_NAME
        description: Product category
        data_tests:
          - not_null
      - name: SUBCATEGORY_NAME
        description: Product subcategory
        data_tests:
          - not_null            
      - name: LISTPRICE
        description: Product price
        data_tests:
          - not_null  
      - name: PRODUCT_NAME
        description: Product name
        data_tests:
          - not_null            

  - name: sat_purchase_order
    description: Satellite for Purchase order data
    columns:
      - name: Purchase_order_hky
        description: Hashkey for Purchase order Hub
        data_tests:
          - not_null          
      - name: LDTS
        description: Loaded date
        data_tests:
          - not_null
      - name: DELETE_FLAG
        description: See if the data is deleted
        data_tests:
          - not_null
      - name: ORDERDATE
        description: Purchase order date
        data_tests:
          - not_null
      - name: SUBTOTAL
        description: Subtotal of the order
        data_tests:
          - not_null            
      - name: TOTALDUE
        description: Total amount due of the PO
        data_tests:
          - not_null

  - name: dim_purchase_order
    description: SCD type 2 for Purchase orders
    columns:
      - name: purchase_order_key
        description: Hashkey for Purchase order
      - name: purchase_order_business_key
        description: Business key for Purchase order       
      - name: delete_flag
        description: Show if the data record has been deleted
      - name: subtotal
        description: Subtotal of the order                
      - name: totaldue
        description: Total of the order            
      - name: valid_from
        description: Shows the date when the record is valid from     
      - name: valid_to
        description: Shows the date when the record is valid to          
      - name: is_current
        description: Shows if the current record is current        

  - name: dim_product
    description: SCD type 2 for Products
    columns:
      - name: product_key
        description: Hashkey for Products
      - name: product_business_key
        description: Business key for Products       
      - name: delete_flag
        description: Show if the data record has been deleted
      - name: category_name
        description: Category name of the product                
      - name: subcategory_name
        description: Subcategory name of the product  
      - name: listprice
        description: List price of the product                   
      - name: valid_from
        description: Shows the date when the record is valid from   
      - name: product_name
        description: Product name             
      - name: valid_to
        description: Shows the date when the record is valid to          
      - name: is_current
        description: Shows if the current record is current           